fusionauth-netcore-client/domain/io/fusionauth/domain/SystemConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/UsageDataConfiguration.cs
Added UsageDataConfiguration in the correct package
=> Merge feature/usage_stats_client

build.savant, fusionauth-netcore-client-test/fusionauth-netcore-client-test/fusionauth-netcore-client-test.csproj, fusionauth-netcore-client/fusionauth-netcore-client.csproj
=> Merge releases/1.54.0

fusionauth-netcore-client/domain/io/fusionauth/domain/APIKey.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/JWTConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/RefreshTokenOneTimeUseConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/RefreshTokenRevocationPolicy.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/provider/BaseSAMLv2IdentityProvider.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/provider/SAMLv2AssertionDecryptionConfiguration.cs
=> Merge pre-release-1.55.0

build.savant, fusionauth-netcore-client-test/fusionauth-netcore-client-test/fusionauth-netcore-client-test.csproj, fusionauth-netcore-client/fusionauth-netcore-client.csproj
=> Merge releases/1.55.1

fusionauth-netcore-client/fusionauth-netcore-client.csproj
Otherwise package looks lonely
=> Add Description for the Nuget package

fusionauth-netcore-client/domain/io/fusionauth/domain/User.cs
=> Merge spencer/eng-2208/user-phoneNumber

fusionauth-netcore-client/domain/io/fusionauth/domain/APIKey.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/JWTConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/RefreshTokenOneTimeUseConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/RefreshTokenRevocationPolicy.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/User.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/provider/SAMLv2AssertionDecryptionConfiguration.cs
=> Merge bhalsey/ENG-2213/merge-develop1

fusionauth-netcore-client/domain/io/fusionauth/domain/UserIdentity.cs
=> Merge wied03/ENG-1/ENG-1757/phone_canon_wo_internal_user

fusionauth-netcore-client/domain/io/fusionauth/domain/api/user/verify/VerifyStartRequest.cs
=> Merge wied03/cleanup

fusionauth-netcore-client/domain/io/fusionauth/domain/LoginIdType.cs
=> Merge bhalsey/ENG-2190/phone_basic_reg

fusionauth-netcore-client/domain/io/fusionauth/domain/api/UserResponse.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/api/VerificationId.cs
=> Merge wied03/ENG-2307/user-api-response-verification

fusionauth-netcore-client/domain/io/fusionauth/domain/ExternalIdentifierConfiguration.cs
=> Merge spencer/eng-1918/ext-id-config

fusionauth-netcore-client/domain/io/fusionauth/domain/ExternalIdentifierConfiguration.cs
=> Merge wied03/ENG-2324/ext-id-replace-email-with-ident

fusionauth-netcore-client/domain/io/fusionauth/domain/PhoneUnverifiedOptions.cs
=> Merge spencer/eng-2350/tenant-identities-tab

build.savant, fusionauth-netcore-client/domain/io/fusionauth/domain/TenantSSOConfiguration.cs, fusionauth-netcore-client/fusionauth-netcore-client.csproj
=> Merge bhalsey/merge-develop-1.56.0

fusionauth-netcore-client/domain/io/fusionauth/domain/ExternalIdentifierConfiguration.cs
=> Merge spencer/eng-2442/phoneNumber-rename

fusionauth-netcore-client/domain/io/fusionauth/domain/Templates.cs
=> Merge wied03/ENG-2419/phone_clickable_link

fusionauth-netcore-client/domain/io/fusionauth/domain/api/LoginResponse.cs
=> Merge wied03/ENG-2304/login_api_verif_if_response

build.savant, fusionauth-netcore-client-test/fusionauth-netcore-client-test/fusionauth-netcore-client-test.csproj, fusionauth-netcore-client/fusionauth-netcore-client.csproj
=> Merge wied03/157_bump

fusionauth-netcore-client/domain/io/fusionauth/domain/WebhookEventLogConfiguration.cs, fusionauth-netcore-client/src/io/fusionauth/FusionAuthClient.cs, fusionauth-netcore-client/src/io/fusionauth/FusionAuthSyncClient.cs, fusionauth-netcore-client/src/io/fusionauth/IFusionAuthClient.cs
=> Merge feature/wel-fix

fusionauth-netcore-client/domain/io/fusionauth/domain/RegistrationConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/api/passwordless/PasswordlessStartRequest.cs
=> Merge bhalsey/ENG-2354/basic_reg_passwordless

fusionauth-netcore-client/domain/io/fusionauth/domain/RegistrationConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/Tenant.cs
=> Merge bhalsey/ENG-2542/add-tenant-password-enabled

fusionauth-netcore-client/domain/io/fusionauth/domain/api/passwordless/PasswordlessStartRequest.cs
=> Merge wied03/ENG-1834/passwordless_start_api

fusionauth-netcore-client/src/io/fusionauth/FusionAuthClient.cs, fusionauth-netcore-client/src/io/fusionauth/FusionAuthSyncClient.cs, fusionauth-netcore-client/src/io/fusionauth/IFusionAuthClient.cs
=> ENG-2608 - New APIs/method overloads

fusionauth-netcore-client/domain/io/fusionauth/domain/TenantPhoneConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/api/user/ChangePasswordRequest.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/api/user/ForgotPasswordRequest.cs
=> Merge spencer/eng-1807/change-password-phone

fusionauth-netcore-client/domain/io/fusionauth/domain/ExternalIdentifierConfiguration.cs
=> Merge wied03/ENG-2546/phone_passwordless_formfield

build.savant, fusionauth-netcore-client/domain/io/fusionauth/domain/SendSetPasswordIdentityType.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/TenantPhoneConfiguration.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/api/UserRequest.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/api/user/RegistrationRequest.cs
=> Merge wied03/ENG-2002/sms-send-set-pass

fusionauth-netcore-client/domain/io/fusionauth/domain/PhoneUnverifiedOptions.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/TenantPhoneConfiguration.cs
=> Merge bhalsey/ENG-2601/admin-ui-identies-tab

fusionauth-netcore-client/domain/io/fusionauth/domain/api/user/verify/VerifyCompleteResponse.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/api/user/verify/VerifyStartRequest.cs, fusionauth-netcore-client/src/io/fusionauth/FusionAuthClient.cs, fusionauth-netcore-client/src/io/fusionauth/FusionAuthSyncClient.cs, fusionauth-netcore-client/src/io/fusionauth/IFusionAuthClient.cs
=> Merge wied03/ENG-2455/identity_verif_api_status

fusionauth-netcore-client/domain/io/fusionauth/domain/WebhookEventLog.cs
=> Merge wied03/ENG-1822/event_serializer_remove

fusionauth-netcore-client/domain/io/fusionauth/domain/Tenant.cs
=> Merge wied03/ENG-2790/password-toggle-resolution

fusionauth-netcore-client/domain/io/fusionauth/domain/api/user/RegistrationRequest.cs
=> Merge wied03/ENG-3152/pre-verified-combo

fusionauth-netcore-client/domain/io/fusionauth/domain/form/FormStep.cs, fusionauth-netcore-client/domain/io/fusionauth/domain/form/FormStepType.cs
=> Merge wied03/ENG-2192/pre-verify-form-api
